"""Delete rol in users table

Revision ID: 06e602bbdcfb
Revises: 01e4e0edad77
Create Date: 2022-12-30 20:29:38.047342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e602bbdcfb'
down_revision = '01e4e0edad77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rol', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
