"""add groups and its relations

Revision ID: 6a86b951648e
Revises: 8885512ae8d4
Create Date: 2023-01-02 20:22:07.240247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a86b951648e'
down_revision = '8885512ae8d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
